### ISSUE TITLE
Just sending it.

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#16]
[15:21:19] [Craft Scheduler Thread - 52/WARN]: Exception in thread "Craft Scheduler Thread - 52"
[15:21:19] [Craft Scheduler Thread - 52/WARN]: org.apache.commons.lang.UnhandledException: Plugin RestrictedCreative v1.12.6 generated an exception while executing task 15523
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
at me.prunt.restrictedcreative.Database.isValidConnection(Database.java:73)
at me.prunt.restrictedcreative.Database.getConnection(Database.java:52)
at me.prunt.restrictedcreative.Main$5.run(Main.java:462)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more

**Comment by Prunt** [comment]
Your SQLite package doesn't support the `#isValid()` method. Try updating your Java or use MySQL.

**Comment by Prunt** [comment]
I'll close the issue for now, I hope you got it sorted out.
