### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#20]
[15:40:22] [Craft Scheduler Thread - 404/WARN]: org.apache.commons.lang.UnhandledException: Plugin RestrictedCreative v1.12.8 generated an exception while executing task 736970
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AbstractMethodError: org.sqlite.Conn.isValid(I)Z
at me.prunt.restrictedcreative.Database.isValidConnection(Database.java:73)
at me.prunt.restrictedcreative.Database.getConnection(Database.java:52)
at me.prunt.restrictedcreative.Main$5.run(Main.java:479)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 4 more

**Comment by Prunt** [comment]
Have you tried any of my suggestions from the last issue? https://github.com/Prunt/RestrictedCreative/issues/16

**Comment by EvilSlime** [comment]
:)
