### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#23]
[11:03:22] [Server thread/ERROR]: Could not pass event PlayerGameModeChangeEvent to RestrictedCreative v1.13org.bukkit.event.EventExceptionat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:850) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at com.earth2me.essentials.commands.Commandgamemode.run(Commandgamemode.java:68) [EssentialsX.jar:?]at com.earth2me.essentials.commands.EssentialsCommand.run(EssentialsCommand.java:157) [EssentialsX.jar:?]at com.earth2me.essentials.Essentials.onCommandEssentials(Essentials.java:517) [EssentialsX.jar:?]at com.earth2me.essentials.Essentials.onCommand(Essentials.java:430) [EssentialsX.jar:?]at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: java.lang.NullPointerExceptionat me.prunt.restrictedcreative.Main.unCreative(Main.java:889) ~[RestrictedCreative.jar:?]at me.prunt.restrictedcreative.listeners.EventListener.onPlayerGameModeChange(EventListener.java:990) ~[RestrictedCreative.jar:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]... 25 more

**Comment by EvilSlime** [comment]
[07:13:52] [Server thread/ERROR]: Could not pass event PlayerGameModeChangeEvent to RestrictedCreative v1.13org.bukkit.event.EventExceptionat org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.setGameMode(CraftPlayer.java:850) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at com.onarandombox.MultiverseCore.listeners.MVPlayerListener$2.run(MVPlayerListener.java:353) [Multiverse-Core.jar:?]at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]Caused by: java.lang.NullPointerExceptionat me.prunt.restrictedcreative.Main.unCreative(Main.java:889) ~[?:?]at me.prunt.restrictedcreative.listeners.EventListener.onPlayerGameModeChange(EventListener.java:990) ~[?:?]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_141]at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_141]at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_141]at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-"4c7641d"]... 13 more
