### ISSUE TITLE
Cannot execute command in RestrictedCreative v1.15.3

### ISSUE THREAD

**Issue by artbnzz** [Prunt/RestrictedCreative#44]
Server paperspigot 1.12.2
[16:42:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'rc' in plugin RestrictedCreative v1.15.3 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1475) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1280) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[16:42:40] [Server thread/ERROR]: Could not pass event CraftItemEvent to Jobs v4.7.0
java.lang.NoClassDefFoundError: Could not initialize class com.gamingmesh.jobs.CMILib.ItemManager$1
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2196) ~[?:?]
	at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:2192) ~[?:?]
	at com.gamingmesh.jobs.listeners.JobsPaymentListener.onInventoryCraft(JobsPaymentListener.java:577) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor748.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1533]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.12.2.jar:git-Paper-1533]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1985) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:849) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:773) ~[patched_1.12.2.jar:git-Paper-1533]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) ~[patched_1.12.2.jar:git-Paper-1533]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by Prunt** [comment]
Well, it says exactly why the command doesn't work: "plugin is disabled". You should inspect you log files to find an error about why it's disabled.

**Comment by artbnzz** [comment]
i don't know. this plugin is still loading........... can't enable it. plugin is not showing error.

**Comment by Prunt** [comment]
You could post a full sever startup log so I could get a better idea what's going on. Or test with 1.15.4 once it comes out to see if the issue persists.
