### ISSUE TITLE
Could not pass event BlockPhysicsEvent to RestrictedCreative v2.0b-BROKEN

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#50]
```
[19:54:27] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to RestrictedCreative v2.0b-BROKEN
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.1.jar:git-Paper-214]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callBlockPhysicsEvent(CraftEventFactory.java:1128) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.BlockPlant.updateState(BlockPlant.java:18) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.BlockTallPlant.updateState(BlockTallPlant.java:17) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.IBlockData.updateState(IBlockData.java:252) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.DefinedStructure.lambda$a$1(DefinedStructure.java:262) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.VoxelShapeDiscrete.a(SourceFile:313) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.VoxelShapeDiscrete.a(SourceFile:282) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.DefinedStructure.a(DefinedStructure.java:252) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.DefinedStructure.a(DefinedStructure.java:141) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.DefinedStructurePiece.a(SourceFile:59) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.WorldGenShipwreck$a.a(SourceFile:139) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.StructureStart.a(SourceFile:62) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.StructureGenerator.generate(StructureGenerator.java:50) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.WorldGenDecoratorEmpty.a(SourceFile:16) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.WorldGenDecoratorEmpty.a(SourceFile:13) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.WorldGenFeatureComposite.a(SourceFile:27) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.BiomeBase.a(SourceFile:504) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkGeneratorAbstract.addDecorations(ChunkGeneratorAbstract.java:98) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.generator.NormalChunkGenerator.addDecorations(NormalChunkGenerator.java:59) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkTaskDecorate.a(SourceFile:12) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkTask.a(SourceFile:35) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:95) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:78) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkTaskScheduler.a(ChunkTaskScheduler.java:16) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:147) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:105) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkStatus.a(SourceFile:22) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:143) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:137) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler$a.a(SourceFile:115) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:61) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.1.jar:git-Paper-214]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R2.Scheduler.a(SourceFile:62) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.SchedulerBatch.a(SourceFile:39) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:121) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.PlayerChunk.a(PlayerChunk.java:98) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.PlayerChunkMap.flush(PlayerChunkMap.java:159) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.WorldServer.doTick(WorldServer.java:322) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1066) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:428) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:936) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:834) ~[patched_1.13.1.jar:git-Paper-214]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: net.minecraft.server.v1_13_R2.ReportedException: Exception generating new chunk
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.a(ChunkProviderServer.java:181) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:126) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:181) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:185) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getChunk(CraftBlock.java:98) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.<init>(CraftBlockState.java:40) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState0(CraftBlock.java:415) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:277) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:271) ~[patched_1.13.1.jar:git-Paper-214]
	at me.prunt.restrictedcreative.listeners.BlockUpdateListener.onBlockUpdate(BlockUpdateListener.java:43) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor933.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-214]
	... 76 more
Caused by: java.lang.RuntimeException: Batch already started.
	at net.minecraft.server.v1_13_R2.SchedulerBatch.b(SourceFile:27) ~[patched_1.13.1.jar:git-Paper-214]
	at net.minecraft.server.v1_13_R2.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:181) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.CraftWorld.getChunkAt(CraftWorld.java:185) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getChunk(CraftBlock.java:98) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlockState.<init>(CraftBlockState.java:40) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState0(CraftBlock.java:415) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:277) ~[patched_1.13.1.jar:git-Paper-214]
	at org.bukkit.craftbukkit.v1_13_R2.block.CraftBlock.getState(CraftBlock.java:271) ~[patched_1.13.1.jar:git-Paper-214]
	at me.prunt.restrictedcreative.listeners.BlockUpdateListener.onBlockUpdate(BlockUpdateListener.java:43) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor933.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.1.jar:git-Paper-214]
	... 76 more
```

**Comment by Prunt** [comment]
Interesting... I'm using a deprecated method where it throws the error, but it shouldn't cause an EventException. I guess I'll use something else then. Hopefully will be fixed in the next version.
