### ISSUE TITLE
PlayerKickEvent, PlayerQuitEvent error

### ISSUE THREAD

**Issue by andris155** [Prunt/RestrictedCreative#80]
```
[19:56:55] [Server thread/INFO]: [ChatControl] [-] pAdAwAn123
[19:57:15] [Server thread/INFO]: drpub lost connection: Disconnected
[19:57:15] [Server thread/INFO]: [ChatControl] [-] drpub
[19:57:25] [Server thread/INFO]: GeryFat issued server command: /p h
[19:57:26] [Server thread/INFO]: ProGam3rHUN_YT issued server command: /warp vadon
[19:57:26] [Server thread/ERROR]: Could not pass event PlayerKickEvent to RestrictedCreative v2.0f-POSSIBLY-BUGGY
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-429]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.disconnect(PlayerConnection.java:258) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.kickPlayer(CraftPlayer.java:424) ~[patched_1.13.2.jar:git-Paper-429]
	at com.earth2me.essentials.User.checkActivity(User.java:586) ~[?:?]
	at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at me.prunt.restrictedcreative.utils.Utils.saveInventory(Utils.java:569) ~[?:?]
	at me.prunt.restrictedcreative.listeners.PlayerMiscListener.onPlayerKick(PlayerMiscListener.java:216) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1027.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-429]
	... 14 more
[19:57:26] [Server thread/INFO]: Woltix_ lost connection: Kidobott a rendszer, mert 15 percnél tovább voltál távol.
[19:57:26] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to RestrictedCreative v2.0f-POSSIBLY-BUGGY
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-429]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1440) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.disconnect(PlayerConnection.java:273) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.entity.CraftPlayer.kickPlayer(CraftPlayer.java:424) ~[patched_1.13.2.jar:git-Paper-429]
	at com.earth2me.essentials.User.checkActivity(User.java:586) ~[?:?]
	at com.earth2me.essentials.EssentialsTimer.run(EssentialsTimer.java:58) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
	at me.prunt.restrictedcreative.utils.Utils.saveInventory(Utils.java:569) ~[?:?]
	at me.prunt.restrictedcreative.listeners.PlayerMiscListener.onPlayerQuit(PlayerMiscListener.java:205) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1026.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-429]
	... 16 more
```

```
[12:07:53] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to RestrictedCreative v2.0f-POSSIBLY-BUGGY
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.2.jar:git-Paper-429]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-429]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:429) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1440) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:349) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:154) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-429]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-429]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ArrayStoreException
	at java.util.ArrayList.toArray(ArrayList.java:412) ~[?:1.8.0_181]
	at me.prunt.restrictedcreative.utils.InventoryUtils.toBase64(InventoryUtils.java:90) ~[?:?]
	at me.prunt.restrictedcreative.utils.PlayerInfo.getEffects(PlayerInfo.java:50) ~[?:?]
	at me.prunt.restrictedcreative.utils.Utils.saveInventory(Utils.java:570) ~[?:?]
	at me.prunt.restrictedcreative.listeners.PlayerMiscListener.onPlayerQuit(PlayerMiscListener.java:205) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1026.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-429]
	... 12 more
[12:07:53] [Server thread/INFO]: [ChatControl] [-] KernelPanic
```

**Comment by hankur** [comment]
Thank you for reporting the bug, but going forward be sure to post v2.0 bugs to the [new Issue Tracker](https://bitbucket.org/Prunt/restrictedcreative/issues?status=open).
